# CREATE INDEX 인덱스이름 on 테이블(칼럼_);

CREATE INDEX STU_PRIM ON STUDENT (STU_NO);

CREATE INDEX ATT_PRIM ON ATTEND (STU_NO);

CREATE INDEX FEE_PRIM ON STUDENT(STU_NO);

CREATE INDEX SUB_PRIM SUBJECT(SUB_CODE);

CREATE INDEX SCO_PRIM ON STUDENT(STU_NO);

CREATE INDEX PRO_PRIM ON PROFESSOR(PROF_CODE);

CREATE INDEX POS_PRIM ON POST(POST_NO);

CREATE INDEX CIR_PRIM ON CIRCLE(CIR_NUM);

CREATE INDEX DEP_PRIM ON DEPARTMENT(DEPT_CODE);
